# -*- coding: utf-8 -*-
"""Basic Python Calculator .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1C3OykvhP7nG4W_xqlxSH6_AXDg4S9213
"""



# ================================
# Basic Calculator with Gradio
# Beginner Python Project for Colab
# ================================

!pip install -q gradio

import gradio as gr

# ------------------ Backend Logic ------------------
def calculator(num1, num2, operation):
    """
    Simple calculator backend logic.
    Takes two numbers and an operation, returns the result.
    """
    try:
        num1 = float(num1)
        num2 = float(num2)

        if operation == "Add":
            result = num1 + num2
        elif operation == "Subtract":
            result = num1 - num2
        elif operation == "Multiply":
            result = num1 * num2
        elif operation == "Divide":
            if num2 == 0:
                return "Error: Cannot divide by zero"
            result = num1 / num2
        else:
            return "Invalid Operation"

        return f"Result: {result}"

    except ValueError:
        return "Error: Please enter valid numbers."

# ------------------ Gradio Interface ------------------
def create_app():
    with gr.Blocks(theme=gr.themes.Default(primary_hue="blue")) as app:
        gr.Markdown("# Basic Python Calculator")


        with gr.Row():
            num1 = gr.Textbox(label="Enter First Number", placeholder="e.g., 10")
            num2 = gr.Textbox(label="Enter Second Number", placeholder="e.g., 5")

        operation = gr.Radio(["Add", "Subtract", "Multiply", "Divide"], label="Select Operation")

        calc_button = gr.Button("Calculate")
        output = gr.Textbox(label="Output")

        calc_button.click(fn=calculator, inputs=[num1, num2, operation], outputs=output)

    return app

# ------------------ Launch App ------------------
if __name__ == "__main__":
    app = create_app()
    app.launch(share=True)